### ISSUE TITLE
Configure key based authentication for Ansible

### ISSUE THREAD

**Issue by StefanoSalsano** [netgroup/kubernetes-playground#80]
when moving to a kvm environment using vagrant vagrant as login and password can be questionable :-)

**Comment by ferrarimarco** [comment]
Hi Stefano. What do you mean? From a security standpoint?

**Comment by StefanoSalsano** [comment]
yes from a security standpoint

**Comment by ferrarimarco** [comment]
How is this different from the Virtualbox provider? In case the KVM environment is shared?

**Comment by StefanoSalsano** [comment]
yes, the configurable password will be used for both Virtualbox and KVM provider... in case of a local usage like a Virtualbox environment I see no reason to change the password, in case of deploying our system in a shared KVM environment I would prefer to have a changeable password as a minimal security measure

**Comment by ferrarimarco** [comment]
After thinking about this, I'm hesitant to implement this feature (I even started working on this).

It's not just a matter of adding the required values to defaults.yaml, but we should also:

1. Configure Ansible to use the customized values.
1. Provision and configure that user in the base box.
1. Delete the vagrant user from the base box.

If security is a concern here, we should instead spend effort to switch to key-based authentication. It should also be easier, because all we have to do in this case is:

1. Provide Ansible with the private keys that Vagrant generates, or provide our own.
1. Remove the Ansible variables that enable password authentication for SSH connections.
1. Remove the script and provisioner that enable password authentication for SSH connections.

I can take care of the issue in both cases, but I strongly suggest the second option (key authentication) if security is a concern.

**Comment by StefanoSalsano** [comment]
sorry @ferrarimarco, I overlooked this message! I was hoping for this approach so it is good for me

I suggest that with the new solution, it should be possible for the vagrant user to ssh to any other node  (master or minion) from any node... in this way it is easy to write scripts that execute commands or copy files, as it can be needed to automate the testing operations...
what do you think?
so it will be even easier than the current approach in which you have to provide the "vagrant" password

**Comment by ferrarimarco** [comment]
OK, it's settled then.

My gut feeling is that this is too big for the 2.1.0 milestone that's almost done. Shall we move this to 2.2.0?

WDYT?

**Comment by ferrarimarco** [comment]
or 2.3.0

**Comment by StefanoSalsano** [comment]
Fine for me whatever works for you it's not blocking for kites

**Comment by ferrarimarco** [comment]
Closing. Will reopen if needed.
